"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const dotenv_1 = require("dotenv");
const user_router_js_1 = __importDefault(require("./routes/user-router.js"));
const product_router_js_1 = __importDefault(require("./routes/product-router.js"));
(0, dotenv_1.config)();
const app = (0, express_1.default)();
const PORT = (_a = process.env.PORT) !== null && _a !== void 0 ? _a : 3000;
app.use(express_1.default.json());
app.use((0, cors_1.default)());
app.use("/api/user", user_router_js_1.default);
app.use("/api/products", product_router_js_1.default);
app.listen(PORT, () => console.log(`Server is running on port ${PORT}`));
exports.default = app;
